// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tiitwrovhvaehriahxcp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpaXR3cm92aHZhZWhyaWFoeGNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE3NjYwNDUsImV4cCI6MjA4NzM0MjA0NX0.wlynWJ7vlkPLL7QD6kYznPARV6V-cs8kPT4zez6UsAQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});